#!/usr/bin/env bash
# Transfers files from client to server
# Accepts four inputs:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.


if [ $# -lt 4 ]
then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
    scp -i "$4" "$1" "$3"@"$2":~
fi