#!/usr/bin/env bash
# Install Nginx web server and set redirect 301

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start

string='#\tif (\$request_filename ~ redirect_me){\
		\n#\t\trewrite ^ https://sketchfab.com/bluepeno/models permanent;\
	\n#\t}'

 sed "90 i $(echo $string)" $
 
 if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi