#!/usr/bin/env bash
# Install and configure haproxy load balancer

setup="\
\\\nfrontend jfrontend\n\
    \tbind *:80\n\
    \tmode http\n\
    \tdefault_backend nginx_servers\n\
\n\
backend nginx_servers\n\
    \tbalance roundrobin\n\
    \tserver web-01 100.27.3.193:80\n\
    \tserver web-02 100.25.165.60:80"

sed -i "\$a$setup" "/etc/haproxy/haproxy.cfg"
